# -*- coding: utf-8 -*-
"""projeto_individual3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NaAKLxAqBcPjgTDRK20DxnMcg8Akyvc

Importações
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Criação do data frame (dicionario)"""

dicionario = [
    {'dia': 'Segunda', 'horas trabalhadas': 6, 'bugs corrigido': 3, 'tarefas concluidas': 5},
     {'dia': 'Terça', 'horas trabalhadas': 7, 'bugs corrigido': 2, 'tarefas concluidas': 4},
      {'dia': 'Quarta', 'horas trabalhadas': 8, 'bugs corrigido': 1, 'tarefas concluidas': 6},
     {'dia': 'Quinta', 'horas trabalhadas': 6, 'bugs corrigido': 4, 'tarefas concluidas': 4},
     {'dia': 'Sexta', 'horas trabalhadas': 7, 'bugs corrigido': 3, 'tarefas concluidas': 5},
     {'dia': 'Sabado', 'horas trabalhadas': 5, 'bugs corrigido': 2, 'tarefas concluidas': 3},
     {'dia': 'Domingo', 'horas trabalhadas': 4, 'bugs corrigido': 1, 'tarefas concluidas': 2}
              ]

df = pd.DataFrame(dicionario)
print(df)

"""Caulculo do total de horas trabalhadas"""

tabela_total_horas_trabalhadas = float(df['horas trabalhadas'].sum())
print(f'Total de horas trabalhadas: {tabela_total_horas_trabalhadas}')

"""Função que calcula a média diaria de horas trabalhadas, com arredondameno de duas casas decimais"""

len_media_horas_trabalhadas = len(df['horas trabalhadas'])
media_horas_trabalhadas = tabela_total_horas_trabalhadas / len_media_horas_trabalhadas
media_horas_trabalhadas = round(media_horas_trabalhadas, 2)
print(media_horas_trabalhadas)

"""Função que calcula o total de bugs"""

total_bugs = float(df['bugs corrigido'].sum())
print(f'Total de Bugs: {total_bugs}')

"""Função que calcula a média de bugs corrigidos"""

media_bugs_corrigidos = round(df['bugs corrigido'].mean(), 2)
print(media_bugs_corrigidos)

"""Função que calcula o Total de tarefas concluidas"""

total_tarefas_concluidas = float(df['tarefas concluidas'].sum())
print(total_tarefas_concluidas)

"""Função que calcula a média diaria de tarefas concluidas"""

media_tarefas_concluidas = round(df['tarefas concluidas'].mean(), 2)
print(media_tarefas_concluidas)

"""Função que calcula a produtividade diaria

"""

produtividade_diaria = total_tarefas_concluidas / tabela_total_horas_trabalhadas
print(produtividade_diaria)

print(df)

"""Adicionando uma coluna "produtividade"
"""

df['produtividade'] = df['tarefas concluidas'] / df['horas trabalhadas']
print(df)

"""Exibe estatísticas descritivas do DataFrame, incluindo média, desvio padrão, valores mínimos e máximos."""

# Estatísticas Descritivas
print("Estatísticas Descritivas:\n")
print(df.describe())

"""Geração de graficos"""

# Configurar o estilo do Seaborn
sns.set(style="whitegrid")

# Gráfico de Barras para Tarefas Concluídas por Dia
plt.figure(figsize=(10, 6))
sns.barplot(x='dia', y='tarefas concluidas', hue='dia', data=df, palette='viridis', dodge=False, legend=False)
plt.title('Tarefas Concluídas por Dia')
plt.xlabel('Dia da Semana')
plt.ylabel('Tarefas Concluídas')
plt.show()

# Gráfico de Barras para Bugs Corrigidos por Dia
plt.figure(figsize=(10, 6))
sns.barplot(x='dia', y='bugs corrigido', hue='dia', data=df, palette='rocket', dodge=False, legend=False)
plt.title('Bugs Corrigidos por Dia')
plt.xlabel('Dia da Semana')
plt.ylabel('Bugs Corrigidos')
plt.show()

# Gráfico de Linhas para Produtividade Diária
plt.figure(figsize=(10, 6))
sns.lineplot(x='dia', y='produtividade', data=df, marker='o', color='b')
plt.title('Produtividade Diária (Tarefas Concluídas por Hora)')
plt.xlabel('Dia da Semana')
plt.ylabel('Produtividade (Tarefas por Hora)')
plt.show()